#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
    NRNHOME="/home/adamimos/anaconda3/envs/NEURON/lib/python3.8/site-packages/neuron/.data"
fi
if test "${NEURONHOME}" = "" ; then
    NEURONHOME=${NRNHOME}/share/nrn
    export NEURONHOME
fi
if test "x${NRNBIN}" = "x" ; then
    NRNBIN="/home/adamimos/anaconda3/envs/NEURON/bin"
fi
if test "" = "yes" ; then
    NRNIV="${NRNBIN}/nrniv.app/Contents/MacOS/nrniv"
else
    NRNIV="${NRNBIN}/nrniv"
fi
"${NRNIV}" -dll "/home/adamimos/Documents/Projects/Godenzini/Archive/x86_64/.libs/libnrnmech.so" "$@"
