#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
	NRNHOME="/Applications/NEURON-7.3/nrn"
fi
if test "x${NRNBIN}" = "x" ; then
	NRNBIN="/Applications/NEURON-7.3/nrn/i386/bin/"
fi
if test "yes" = "yes" ; then
	NRNIV="${NRNBIN}nrniv.app/Contents/MacOS/nrniv"
else
	NRNIV="${NRNBIN}nrniv"
fi
"${NRNIV}" -dll "/Users/adamimos/LarkumLab/Lucy L23 Project/Basic Setup 53/i386/.libs/libnrnmech.so" "$@"
